/**
 * GeoJSON polygons for Tijuana zones.
 * Generated by scripts/fetch-polygons.ts from OpenStreetMap data.
 * Coordinates in GeoJSON standard [lng, lat] order.
 *
 * Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ZONE_GEOJSON: GeoJSON.FeatureCollection = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": 0,
      "properties": {
        "slug": "zona-rio",
        "name": "Zona Río"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.05,
              32.526
            ],
            [
              -117.02,
              32.526
            ],
            [
              -117.02,
              32.506
            ],
            [
              -117.05,
              32.506
            ],
            [
              -117.05,
              32.526
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 1,
      "properties": {
        "slug": "playas-de-tijuana",
        "name": "Playas de Tijuana"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.14,
              32.54
            ],
            [
              -117.105,
              32.54
            ],
            [
              -117.105,
              32.51
            ],
            [
              -117.14,
              32.51
            ],
            [
              -117.14,
              32.54
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 2,
      "properties": {
        "slug": "otay",
        "name": "Otay"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.98,
              32.555
            ],
            [
              -116.945,
              32.555
            ],
            [
              -116.945,
              32.53
            ],
            [
              -116.98,
              32.53
            ],
            [
              -116.98,
              32.555
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 3,
      "properties": {
        "slug": "chapultepec",
        "name": "Chapultepec"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.015,
              32.51
            ],
            [
              -116.995,
              32.51
            ],
            [
              -116.995,
              32.49
            ],
            [
              -117.015,
              32.49
            ],
            [
              -117.015,
              32.51
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 4,
      "properties": {
        "slug": "hipodromo",
        "name": "Hipódromo"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.005,
              32.52
            ],
            [
              -116.985,
              32.52
            ],
            [
              -116.985,
              32.5
            ],
            [
              -117.005,
              32.5
            ],
            [
              -117.005,
              32.52
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 5,
      "properties": {
        "slug": "centro",
        "name": "Centro"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.05,
              32.54
            ],
            [
              -117.025,
              32.54
            ],
            [
              -117.025,
              32.525
            ],
            [
              -117.05,
              32.525
            ],
            [
              -117.05,
              32.54
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 6,
      "properties": {
        "slug": "residencial-del-bosque",
        "name": "Residencial del Bosque"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.935,
              32.48
            ],
            [
              -116.91,
              32.48
            ],
            [
              -116.91,
              32.46
            ],
            [
              -116.935,
              32.46
            ],
            [
              -116.935,
              32.48
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 7,
      "properties": {
        "slug": "la-mesa",
        "name": "La Mesa"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.975,
              32.515
            ],
            [
              -116.95,
              32.515
            ],
            [
              -116.95,
              32.49
            ],
            [
              -116.975,
              32.49
            ],
            [
              -116.975,
              32.515
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 8,
      "properties": {
        "slug": "cacho",
        "name": "Cacho"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.035,
              32.53
            ],
            [
              -117.015,
              32.53
            ],
            [
              -117.015,
              32.515
            ],
            [
              -117.035,
              32.515
            ],
            [
              -117.035,
              32.53
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 9,
      "properties": {
        "slug": "agua-caliente",
        "name": "Agua Caliente"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.01,
              32.515
            ],
            [
              -116.988,
              32.515
            ],
            [
              -116.988,
              32.498
            ],
            [
              -117.01,
              32.498
            ],
            [
              -117.01,
              32.515
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 10,
      "properties": {
        "slug": "lomas-de-agua-caliente",
        "name": "Lomas de Agua Caliente"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.005,
              32.498
            ],
            [
              -116.98,
              32.498
            ],
            [
              -116.98,
              32.478
            ],
            [
              -117.005,
              32.478
            ],
            [
              -117.005,
              32.498
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 11,
      "properties": {
        "slug": "libertad",
        "name": "Libertad"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.06,
              32.545
            ],
            [
              -117.04,
              32.545
            ],
            [
              -117.04,
              32.53
            ],
            [
              -117.06,
              32.53
            ],
            [
              -117.06,
              32.545
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 12,
      "properties": {
        "slug": "soler",
        "name": "Soler"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.055,
              32.535
            ],
            [
              -117.038,
              32.535
            ],
            [
              -117.038,
              32.52
            ],
            [
              -117.055,
              32.52
            ],
            [
              -117.055,
              32.535
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 13,
      "properties": {
        "slug": "federal",
        "name": "Federal"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.045,
              32.55
            ],
            [
              -117.025,
              32.55
            ],
            [
              -117.025,
              32.538
            ],
            [
              -117.045,
              32.538
            ],
            [
              -117.045,
              32.55
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 14,
      "properties": {
        "slug": "baja-malibu",
        "name": "Baja Malibú"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.125,
              32.49
            ],
            [
              -117.105,
              32.49
            ],
            [
              -117.105,
              32.47
            ],
            [
              -117.125,
              32.47
            ],
            [
              -117.125,
              32.49
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 15,
      "properties": {
        "slug": "real-del-mar",
        "name": "Real del Mar"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.12,
              32.47
            ],
            [
              -117.095,
              32.47
            ],
            [
              -117.095,
              32.45
            ],
            [
              -117.12,
              32.45
            ],
            [
              -117.12,
              32.47
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 16,
      "properties": {
        "slug": "san-antonio-del-mar",
        "name": "San Antonio del Mar"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.105,
              32.45
            ],
            [
              -117.08,
              32.45
            ],
            [
              -117.08,
              32.425
            ],
            [
              -117.105,
              32.425
            ],
            [
              -117.105,
              32.45
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 17,
      "properties": {
        "slug": "punta-bandera",
        "name": "Punta Bandera"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.115,
              32.445
            ],
            [
              -117.09,
              32.445
            ],
            [
              -117.09,
              32.425
            ],
            [
              -117.115,
              32.425
            ],
            [
              -117.115,
              32.445
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 18,
      "properties": {
        "slug": "costa-coronado",
        "name": "Costa Coronado"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.11,
              32.43
            ],
            [
              -117.085,
              32.43
            ],
            [
              -117.085,
              32.41
            ],
            [
              -117.11,
              32.41
            ],
            [
              -117.11,
              32.43
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 19,
      "properties": {
        "slug": "las-americas",
        "name": "Las Américas"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.965,
              32.54
            ],
            [
              -116.94,
              32.54
            ],
            [
              -116.94,
              32.52
            ],
            [
              -116.965,
              32.52
            ],
            [
              -116.965,
              32.54
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 20,
      "properties": {
        "slug": "villa-fontana",
        "name": "Villa Fontana"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.95,
              32.525
            ],
            [
              -116.925,
              32.525
            ],
            [
              -116.925,
              32.505
            ],
            [
              -116.95,
              32.505
            ],
            [
              -116.95,
              32.525
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 21,
      "properties": {
        "slug": "montecarlo",
        "name": "Montecarlo"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.945,
              32.51
            ],
            [
              -116.92,
              32.51
            ],
            [
              -116.92,
              32.49
            ],
            [
              -116.945,
              32.49
            ],
            [
              -116.945,
              32.51
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 22,
      "properties": {
        "slug": "otay-universidad",
        "name": "Otay Universidad"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.975,
              32.545
            ],
            [
              -116.95,
              32.545
            ],
            [
              -116.95,
              32.525
            ],
            [
              -116.975,
              32.525
            ],
            [
              -116.975,
              32.545
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 23,
      "properties": {
        "slug": "santa-fe",
        "name": "Santa Fe"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.06,
              32.455
            ],
            [
              -117.035,
              32.455
            ],
            [
              -117.035,
              32.43
            ],
            [
              -117.06,
              32.43
            ],
            [
              -117.06,
              32.455
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 24,
      "properties": {
        "slug": "natura",
        "name": "Natura"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.05,
              32.44
            ],
            [
              -117.025,
              32.44
            ],
            [
              -117.025,
              32.42
            ],
            [
              -117.05,
              32.42
            ],
            [
              -117.05,
              32.44
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 25,
      "properties": {
        "slug": "colinas-de-california",
        "name": "Colinas de California"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.04,
              32.5
            ],
            [
              -117.02,
              32.5
            ],
            [
              -117.02,
              32.48
            ],
            [
              -117.04,
              32.48
            ],
            [
              -117.04,
              32.5
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 26,
      "properties": {
        "slug": "lomas-virreyes",
        "name": "Lomas Virreyes"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.035,
              32.49
            ],
            [
              -117.015,
              32.49
            ],
            [
              -117.015,
              32.47
            ],
            [
              -117.035,
              32.47
            ],
            [
              -117.035,
              32.49
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 27,
      "properties": {
        "slug": "insurgentes",
        "name": "Insurgentes"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.05,
              32.48
            ],
            [
              -117.03,
              32.48
            ],
            [
              -117.03,
              32.46
            ],
            [
              -117.05,
              32.46
            ],
            [
              -117.05,
              32.48
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 28,
      "properties": {
        "slug": "el-florido",
        "name": "El Florido"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.89,
              32.48
            ],
            [
              -116.85,
              32.48
            ],
            [
              -116.85,
              32.45
            ],
            [
              -116.89,
              32.45
            ],
            [
              -116.89,
              32.48
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 29,
      "properties": {
        "slug": "terrazas-de-la-presa",
        "name": "Terrazas de la Presa"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.92,
              32.455
            ],
            [
              -116.89,
              32.455
            ],
            [
              -116.89,
              32.43
            ],
            [
              -116.92,
              32.43
            ],
            [
              -116.92,
              32.455
            ]
          ]
        ]
      }
    }
  ]
} as any

/** Compute centroid of a zone polygon by averaging all coordinates */
export function getZoneCentroid(slug: string): [number, number] | null {
  const feature = ZONE_GEOJSON.features.find(
    (f) => (f.properties as { slug: string }).slug === slug
  )
  if (!feature || feature.geometry.type !== "Polygon") return null

  const coords = (feature.geometry as GeoJSON.Polygon).coordinates[0]
  const len = coords.length - 1 // exclude closing point
  if (len <= 0) return null

  let lngSum = 0
  let latSum = 0
  for (let i = 0; i < len; i++) {
    lngSum += coords[i][0]
    latSum += coords[i][1]
  }
  return [lngSum / len, latSum / len]
}

// Choropleth color scale based on price per m2
export function getPriceColor(pricePerM2: number): string {
  if (pricePerM2 >= 40000) return "#1e40af" // dark blue — premium
  if (pricePerM2 >= 32000) return "#3b82f6" // blue
  if (pricePerM2 >= 26000) return "#60a5fa" // light blue
  if (pricePerM2 >= 20000) return "#93c5fd" // pale blue
  return "#bfdbfe"                           // very pale
}

export function getPriceLabel(pricePerM2: number): string {
  if (pricePerM2 >= 40000) return "Premium"
  if (pricePerM2 >= 32000) return "Alto"
  if (pricePerM2 >= 26000) return "Medio-Alto"
  if (pricePerM2 >= 20000) return "Medio"
  return "Accesible"
}

// Mapbox uses [lng, lat] order
export const TIJUANA_CENTER: [number, number] = [-117.000, 32.490]
export const TIJUANA_BOUNDS: [[number, number], [number, number]] = [
  [-117.200, 32.360], // southwest
  [-116.750, 32.600], // northeast
]
