/**
 * GeoJSON polygons for Tijuana zones.
 * Generated by scripts/fetch-polygons.ts from OpenStreetMap data.
 * Coordinates in GeoJSON standard [lng, lat] order.
 *
 * Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ZONE_GEOJSON: GeoJSON.FeatureCollection = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": 0,
      "properties": {
        "slug": "zona-rio",
        "name": "Zona Río"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.040198,
              32.541491
            ],
            [
              -117.034808,
              32.538746
            ],
            [
              -117.034539,
              32.538472
            ],
            [
              -117.033987,
              32.537492
            ],
            [
              -117.033804,
              32.535701
            ],
            [
              -117.03211,
              32.535772
            ],
            [
              -117.031971,
              32.534529
            ],
            [
              -117.031431,
              32.534589
            ],
            [
              -117.030395,
              32.533056
            ],
            [
              -117.03008,
              32.532188
            ],
            [
              -117.029833,
              32.531826
            ],
            [
              -117.02554,
              32.526536
            ],
            [
              -117.024646,
              32.525956
            ],
            [
              -117.024445,
              32.524664
            ],
            [
              -117.018189,
              32.521371
            ],
            [
              -117.015708,
              32.520348
            ],
            [
              -117.015877,
              32.520026
            ],
            [
              -117.015329,
              32.519764
            ],
            [
              -117.015448,
              32.519546
            ],
            [
              -117.013408,
              32.518589
            ],
            [
              -117.01325,
              32.518431
            ],
            [
              -117.01249,
              32.518063
            ],
            [
              -117.012004,
              32.518614
            ],
            [
              -117.009473,
              32.517894
            ],
            [
              -117.008789,
              32.517627
            ],
            [
              -117.007686,
              32.516813
            ],
            [
              -117.006895,
              32.516647
            ],
            [
              -117.006231,
              32.516717
            ],
            [
              -117.00559,
              32.517013
            ],
            [
              -117.005191,
              32.517417
            ],
            [
              -117.005,
              32.517903
            ],
            [
              -117.001957,
              32.517724
            ],
            [
              -117.000801,
              32.51721
            ],
            [
              -117.000581,
              32.517019
            ],
            [
              -117.000373,
              32.517087
            ],
            [
              -117.000548,
              32.518926
            ],
            [
              -117.000713,
              32.519764
            ],
            [
              -117.00113,
              32.519827
            ],
            [
              -117.001734,
              32.520048
            ],
            [
              -117.007229,
              32.52541
            ],
            [
              -117.009786,
              32.527274
            ],
            [
              -117.010786,
              32.52819
            ],
            [
              -117.011241,
              32.52872
            ],
            [
              -117.011903,
              32.530016
            ],
            [
              -117.011711,
              32.529414
            ],
            [
              -117.011952,
              32.529267
            ],
            [
              -117.013127,
              32.531724
            ],
            [
              -117.014507,
              32.533821
            ],
            [
              -117.014807,
              32.534517
            ],
            [
              -117.016444,
              32.536236
            ],
            [
              -117.018718,
              32.537845
            ],
            [
              -117.019287,
              32.536967
            ],
            [
              -117.023462,
              32.538717
            ],
            [
              -117.024145,
              32.538963
            ],
            [
              -117.024597,
              32.539028
            ],
            [
              -117.025434,
              32.539349
            ],
            [
              -117.025776,
              32.539719
            ],
            [
              -117.0259,
              32.540151
            ],
            [
              -117.025746,
              32.540583
            ],
            [
              -117.025522,
              32.540795
            ],
            [
              -117.025135,
              32.540978
            ],
            [
              -117.025172,
              32.541039
            ],
            [
              -117.025773,
              32.540796
            ],
            [
              -117.025877,
              32.540987
            ],
            [
              -117.026569,
              32.541119
            ],
            [
              -117.027016,
              32.541326
            ],
            [
              -117.027138,
              32.541297
            ],
            [
              -117.028228,
              32.542566
            ],
            [
              -117.030409,
              32.542384
            ],
            [
              -117.030393,
              32.542146
            ],
            [
              -117.029609,
              32.541374
            ],
            [
              -117.029553,
              32.541225
            ],
            [
              -117.029991,
              32.540899
            ],
            [
              -117.031498,
              32.540214
            ],
            [
              -117.034379,
              32.542009
            ],
            [
              -117.040198,
              32.541491
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 1,
      "properties": {
        "slug": "playas-de-tijuana",
        "name": "Playas de Tijuana"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-117.100534, 32.535563],
            [-117.103103, 32.531945],
            [-117.102449, 32.523855],
            [-117.101253, 32.519376],
            [-117.107371, 32.523044],
            [-117.108042, 32.522413],
            [-117.108940, 32.515594],
            [-117.113579, 32.508583],
            [-117.116355, 32.504417],
            [-117.118002, 32.500311],
            [-117.121604, 32.496202],
            [-117.123477, 32.494611],
            [-117.124301, 32.505047],
            [-117.124601, 32.512386],
            [-117.123925, 32.520359],
            [-117.123850, 32.527635],
            [-117.124075, 32.534216],
            [-117.109308, 32.535587],
            [-117.099729, 32.536457],
            [-117.100534, 32.535563]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 2,
      "properties": {
        "slug": "otay",
        "name": "Otay"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.027336,
              32.542596
            ],
            [
              -117.020862,
              32.539311
            ],
            [
              -117.016168,
              32.536145
            ],
            [
              -117.013003,
              32.533025
            ],
            [
              -117.010766,
              32.528054
            ],
            [
              -117.009483,
              32.527054
            ],
            [
              -117.0067,
              32.525155
            ],
            [
              -117.000845,
              32.519317
            ],
            [
              -117.000117,
              32.518818
            ],
            [
              -116.99949,
              32.518387
            ],
            [
              -116.998451,
              32.518093
            ],
            [
              -116.997352,
              32.517939
            ],
            [
              -116.994613,
              32.517731
            ],
            [
              -116.993533,
              32.517666
            ],
            [
              -116.991737,
              32.517536
            ],
            [
              -116.990892,
              32.517466
            ],
            [
              -116.988972,
              32.517319
            ],
            [
              -116.987304,
              32.517193
            ],
            [
              -116.985386,
              32.517045
            ],
            [
              -116.98452,
              32.516968
            ],
            [
              -116.981204,
              32.516673
            ],
            [
              -116.978794,
              32.516458
            ],
            [
              -116.976801,
              32.516281
            ],
            [
              -116.974732,
              32.516097
            ],
            [
              -116.971653,
              32.515569
            ],
            [
              -116.970202,
              32.515426
            ],
            [
              -116.968718,
              32.515327
            ],
            [
              -116.962418,
              32.514956
            ],
            [
              -116.962753,
              32.515727
            ],
            [
              -116.962833,
              32.516036
            ],
            [
              -116.962833,
              32.516798
            ],
            [
              -116.962868,
              32.517018
            ],
            [
              -116.963136,
              32.517959
            ],
            [
              -116.963143,
              32.518148
            ],
            [
              -116.963015,
              32.521222
            ],
            [
              -116.962848,
              32.522066
            ],
            [
              -116.962616,
              32.522503
            ],
            [
              -116.961831,
              32.523331
            ],
            [
              -116.961626,
              32.523723
            ],
            [
              -116.961544,
              32.524097
            ],
            [
              -116.96154,
              32.524475
            ],
            [
              -116.961718,
              32.525112
            ],
            [
              -116.96188,
              32.526003
            ],
            [
              -116.961815,
              32.52628
            ],
            [
              -116.961631,
              32.526659
            ],
            [
              -116.961403,
              32.526916
            ],
            [
              -116.961062,
              32.527217
            ],
            [
              -116.959509,
              32.528288
            ],
            [
              -116.955581,
              32.530567
            ],
            [
              -116.952968,
              32.532096
            ],
            [
              -116.952474,
              32.53238
            ],
            [
              -116.949707,
              32.533127
            ],
            [
              -116.948971,
              32.534067
            ],
            [
              -116.948862,
              32.534572
            ],
            [
              -116.948825,
              32.534963
            ],
            [
              -116.94823,
              32.539135
            ],
            [
              -116.947741,
              32.542592
            ],
            [
              -116.947578,
              32.543825
            ],
            [
              -116.94764,
              32.544347
            ],
            [
              -116.947674,
              32.544559
            ],
            [
              -116.948495,
              32.547548
            ],
            [
              -116.949124,
              32.548462
            ],
            [
              -116.950098,
              32.54915
            ],
            [
              -117.000445,
              32.54489
            ],
            [
              -117.023051,
              32.542989
            ],
            [
              -117.027336,
              32.542596
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 3,
      "properties": {
        "slug": "chapultepec",
        "name": "Chapultepec"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.015,
              32.51
            ],
            [
              -116.995,
              32.51
            ],
            [
              -116.995,
              32.49
            ],
            [
              -117.015,
              32.49
            ],
            [
              -117.015,
              32.51
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 4,
      "properties": {
        "slug": "hipodromo",
        "name": "Hipódromo"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.000172,
              32.503979
            ],
            [
              -117.000108,
              32.503458
            ],
            [
              -116.998438,
              32.503566
            ],
            [
              -116.998246,
              32.503663
            ],
            [
              -116.998567,
              32.504825
            ],
            [
              -116.998836,
              32.504785
            ],
            [
              -116.999569,
              32.507979
            ],
            [
              -116.999572,
              32.508149
            ],
            [
              -116.999547,
              32.508326
            ],
            [
              -116.999867,
              32.508348
            ],
            [
              -116.999991,
              32.508293
            ],
            [
              -116.999788,
              32.508014
            ],
            [
              -116.999735,
              32.507903
            ],
            [
              -116.999534,
              32.506986
            ],
            [
              -116.999292,
              32.505848
            ],
            [
              -116.998973,
              32.504242
            ],
            [
              -116.999352,
              32.50419
            ],
            [
              -117.000125,
              32.504091
            ],
            [
              -117.000172,
              32.503979
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 5,
      "properties": {
        "slug": "centro",
        "name": "Centro"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.05,
              32.54
            ],
            [
              -117.025,
              32.54
            ],
            [
              -117.025,
              32.525
            ],
            [
              -117.05,
              32.525
            ],
            [
              -117.05,
              32.54
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 6,
      "properties": {
        "slug": "residencial-del-bosque",
        "name": "Residencial del Bosque"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.935,
              32.48
            ],
            [
              -116.91,
              32.48
            ],
            [
              -116.91,
              32.46
            ],
            [
              -116.935,
              32.46
            ],
            [
              -116.935,
              32.48
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 7,
      "properties": {
        "slug": "la-mesa",
        "name": "La Mesa"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.975,
              32.515
            ],
            [
              -116.95,
              32.515
            ],
            [
              -116.95,
              32.49
            ],
            [
              -116.975,
              32.49
            ],
            [
              -116.975,
              32.515
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 8,
      "properties": {
        "slug": "cacho",
        "name": "Cacho"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.035,
              32.53
            ],
            [
              -117.015,
              32.53
            ],
            [
              -117.015,
              32.515
            ],
            [
              -117.035,
              32.515
            ],
            [
              -117.035,
              32.53
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 9,
      "properties": {
        "slug": "agua-caliente",
        "name": "Agua Caliente"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.01,
              32.515
            ],
            [
              -116.988,
              32.515
            ],
            [
              -116.988,
              32.498
            ],
            [
              -117.01,
              32.498
            ],
            [
              -117.01,
              32.515
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 10,
      "properties": {
        "slug": "lomas-de-agua-caliente",
        "name": "Lomas de Agua Caliente"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.005,
              32.498
            ],
            [
              -116.98,
              32.498
            ],
            [
              -116.98,
              32.478
            ],
            [
              -117.005,
              32.478
            ],
            [
              -117.005,
              32.498
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 11,
      "properties": {
        "slug": "libertad",
        "name": "Libertad"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.06,
              32.545
            ],
            [
              -117.04,
              32.545
            ],
            [
              -117.04,
              32.53
            ],
            [
              -117.06,
              32.53
            ],
            [
              -117.06,
              32.545
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 12,
      "properties": {
        "slug": "soler",
        "name": "Soler"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.055,
              32.535
            ],
            [
              -117.038,
              32.535
            ],
            [
              -117.038,
              32.52
            ],
            [
              -117.055,
              32.52
            ],
            [
              -117.055,
              32.535
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 13,
      "properties": {
        "slug": "federal",
        "name": "Federal"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.045,
              32.55
            ],
            [
              -117.025,
              32.55
            ],
            [
              -117.025,
              32.538
            ],
            [
              -117.045,
              32.538
            ],
            [
              -117.045,
              32.55
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 14,
      "properties": {
        "slug": "baja-malibu",
        "name": "Baja Malibú"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.125,
              32.49
            ],
            [
              -117.105,
              32.49
            ],
            [
              -117.105,
              32.47
            ],
            [
              -117.125,
              32.47
            ],
            [
              -117.125,
              32.49
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 15,
      "properties": {
        "slug": "real-del-mar",
        "name": "Real del Mar"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.12,
              32.47
            ],
            [
              -117.095,
              32.47
            ],
            [
              -117.095,
              32.45
            ],
            [
              -117.12,
              32.45
            ],
            [
              -117.12,
              32.47
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 16,
      "properties": {
        "slug": "san-antonio-del-mar",
        "name": "San Antonio del Mar"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.105,
              32.45
            ],
            [
              -117.08,
              32.45
            ],
            [
              -117.08,
              32.425
            ],
            [
              -117.105,
              32.425
            ],
            [
              -117.105,
              32.45
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 17,
      "properties": {
        "slug": "punta-bandera",
        "name": "Punta Bandera"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.115,
              32.445
            ],
            [
              -117.09,
              32.445
            ],
            [
              -117.09,
              32.425
            ],
            [
              -117.115,
              32.425
            ],
            [
              -117.115,
              32.445
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 18,
      "properties": {
        "slug": "costa-coronado",
        "name": "Costa Coronado"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.11,
              32.43
            ],
            [
              -117.085,
              32.43
            ],
            [
              -117.085,
              32.41
            ],
            [
              -117.11,
              32.41
            ],
            [
              -117.11,
              32.43
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 19,
      "properties": {
        "slug": "las-americas",
        "name": "Las Américas"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.110353,
              32.522113
            ],
            [
              -117.109492,
              32.522538
            ],
            [
              -117.109494,
              32.523004
            ],
            [
              -117.110328,
              32.523018
            ],
            [
              -117.110353,
              32.522113
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 20,
      "properties": {
        "slug": "villa-fontana",
        "name": "Villa Fontana"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.95,
              32.525
            ],
            [
              -116.925,
              32.525
            ],
            [
              -116.925,
              32.505
            ],
            [
              -116.95,
              32.505
            ],
            [
              -116.95,
              32.525
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 21,
      "properties": {
        "slug": "montecarlo",
        "name": "Montecarlo"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.945,
              32.51
            ],
            [
              -116.92,
              32.51
            ],
            [
              -116.92,
              32.49
            ],
            [
              -116.945,
              32.49
            ],
            [
              -116.945,
              32.51
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 22,
      "properties": {
        "slug": "otay-universidad",
        "name": "Otay Universidad"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.976848,
              32.529501
            ],
            [
              -116.976307,
              32.52407
            ],
            [
              -116.973378,
              32.523386
            ],
            [
              -116.970899,
              32.522814
            ],
            [
              -116.972147,
              32.524946
            ],
            [
              -116.97282,
              32.524898
            ],
            [
              -116.97329,
              32.529704
            ],
            [
              -116.976848,
              32.529501
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 23,
      "properties": {
        "slug": "santa-fe",
        "name": "Santa Fe"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.06,
              32.455
            ],
            [
              -117.035,
              32.455
            ],
            [
              -117.035,
              32.43
            ],
            [
              -117.06,
              32.43
            ],
            [
              -117.06,
              32.455
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 24,
      "properties": {
        "slug": "natura",
        "name": "Natura"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.05,
              32.44
            ],
            [
              -117.025,
              32.44
            ],
            [
              -117.025,
              32.42
            ],
            [
              -117.05,
              32.42
            ],
            [
              -117.05,
              32.44
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 25,
      "properties": {
        "slug": "colinas-de-california",
        "name": "Colinas de California"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.04,
              32.5
            ],
            [
              -117.02,
              32.5
            ],
            [
              -117.02,
              32.48
            ],
            [
              -117.04,
              32.48
            ],
            [
              -117.04,
              32.5
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 26,
      "properties": {
        "slug": "lomas-virreyes",
        "name": "Lomas Virreyes"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.035,
              32.49
            ],
            [
              -117.015,
              32.49
            ],
            [
              -117.015,
              32.47
            ],
            [
              -117.035,
              32.47
            ],
            [
              -117.035,
              32.49
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 27,
      "properties": {
        "slug": "insurgentes",
        "name": "Insurgentes"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.05,
              32.48
            ],
            [
              -117.03,
              32.48
            ],
            [
              -117.03,
              32.46
            ],
            [
              -117.05,
              32.46
            ],
            [
              -117.05,
              32.48
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 28,
      "properties": {
        "slug": "el-florido",
        "name": "El Florido"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.921552,
              32.456944
            ],
            [
              -116.921276,
              32.456695
            ],
            [
              -116.921035,
              32.456611
            ],
            [
              -116.920831,
              32.456783
            ],
            [
              -116.921244,
              32.457156
            ],
            [
              -116.921552,
              32.456944
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "id": 29,
      "properties": {
        "slug": "terrazas-de-la-presa",
        "name": "Terrazas de la Presa"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.92,
              32.455
            ],
            [
              -116.89,
              32.455
            ],
            [
              -116.89,
              32.43
            ],
            [
              -116.92,
              32.43
            ],
            [
              -116.92,
              32.455
            ]
          ]
        ]
      }
    }
  ]
} as any

/** Compute centroid of a zone polygon by averaging all coordinates */
export function getZoneCentroid(slug: string): [number, number] | null {
  const feature = ZONE_GEOJSON.features.find(
    (f) => (f.properties as { slug: string }).slug === slug
  )
  if (!feature || feature.geometry.type !== "Polygon") return null

  const coords = (feature.geometry as GeoJSON.Polygon).coordinates[0]
  const len = coords.length - 1 // exclude closing point
  if (len <= 0) return null

  let lngSum = 0
  let latSum = 0
  for (let i = 0; i < len; i++) {
    lngSum += coords[i][0]
    latSum += coords[i][1]
  }
  return [lngSum / len, latSum / len]
}

// Choropleth color scale based on price per m2
export function getPriceColor(pricePerM2: number): string {
  if (pricePerM2 >= 40000) return "#1e40af" // dark blue — premium
  if (pricePerM2 >= 32000) return "#3b82f6" // blue
  if (pricePerM2 >= 26000) return "#60a5fa" // light blue
  if (pricePerM2 >= 20000) return "#93c5fd" // pale blue
  return "#bfdbfe"                           // very pale
}

export function getPriceLabel(pricePerM2: number): string {
  if (pricePerM2 >= 40000) return "Premium"
  if (pricePerM2 >= 32000) return "Alto"
  if (pricePerM2 >= 26000) return "Medio-Alto"
  if (pricePerM2 >= 20000) return "Medio"
  return "Accesible"
}

// Mapbox uses [lng, lat] order
export const TIJUANA_CENTER: [number, number] = [-117.000, 32.490]
export const TIJUANA_BOUNDS: [[number, number], [number, number]] = [
  [-117.200, 32.360], // southwest
  [-116.750, 32.600], // northeast
]
