/**
 * Demographic data per zone from INEGI Censo 2020 (SCINCE).
 * Generated by scripts/import-inegi.ts
 *
 * Source: INEGI SCINCE 2020 via SEDATU GeoServer
 * Note: Encuesta Intercensal 2025 estará disponible en septiembre 2026.
 */

export interface ZoneDemographics {
  zone_slug: string
  population: number
  households: number
  occupied_dwellings: number
  avg_occupants: number
  pct_internet: number
  pct_car: number
  pct_social_security: number
  economically_active: number
  median_age: number
  ageb_count: number
}

const ZONE_DEMOGRAPHICS: ZoneDemographics[] = [
  {
    "zone_slug": "zona-rio",
    "population": 9510,
    "households": 3545,
    "occupied_dwellings": 3551,
    "avg_occupants": 2.6,
    "pct_internet": 75.6,
    "pct_car": 60.3,
    "pct_social_security": 61.5,
    "economically_active": 5633,
    "median_age": 35.7,
    "ageb_count": 5
  },
  {
    "zone_slug": "playas-de-tijuana",
    "population": 44410,
    "households": 14344,
    "occupied_dwellings": 14357,
    "avg_occupants": 3.1,
    "pct_internet": 81,
    "pct_car": 77,
    "pct_social_security": 62.2,
    "economically_active": 22268,
    "median_age": 35.8,
    "ageb_count": 19
  },
  {
    "zone_slug": "otay",
    "population": 78504,
    "households": 24941,
    "occupied_dwellings": 24952,
    "avg_occupants": 3.1,
    "pct_internet": 76.8,
    "pct_car": 67.9,
    "pct_social_security": 68.1,
    "economically_active": 43928,
    "median_age": 34.4,
    "ageb_count": 30
  },
  {
    "zone_slug": "chapultepec",
    "population": 21850,
    "households": 7384,
    "occupied_dwellings": 7388,
    "avg_occupants": 3,
    "pct_internet": 93,
    "pct_car": 90.2,
    "pct_social_security": 78,
    "economically_active": 12474,
    "median_age": 39.7,
    "ageb_count": 7
  },
  {
    "zone_slug": "hipodromo",
    "population": 0,
    "households": 0,
    "occupied_dwellings": 0,
    "avg_occupants": 0,
    "pct_internet": 0,
    "pct_car": 0,
    "pct_social_security": 0,
    "economically_active": 0,
    "median_age": 0,
    "ageb_count": 0
  },
  {
    "zone_slug": "centro",
    "population": 12490,
    "households": 5052,
    "occupied_dwellings": 5061,
    "avg_occupants": 2.4,
    "pct_internet": 68,
    "pct_car": 37.8,
    "pct_social_security": 61.3,
    "economically_active": 8242,
    "median_age": 35.2,
    "ageb_count": 5
  },
  {
    "zone_slug": "residencial-del-bosque",
    "population": 208360,
    "households": 60627,
    "occupied_dwellings": 60649,
    "avg_occupants": 3.4,
    "pct_internet": 77,
    "pct_car": 65.8,
    "pct_social_security": 76,
    "economically_active": 114404,
    "median_age": 28.9,
    "ageb_count": 64
  },
  {
    "zone_slug": "la-mesa",
    "population": 50824,
    "households": 16326,
    "occupied_dwellings": 16345,
    "avg_occupants": 3.1,
    "pct_internet": 82.3,
    "pct_car": 72.5,
    "pct_social_security": 71.5,
    "economically_active": 28492,
    "median_age": 33.6,
    "ageb_count": 18
  },
  {
    "zone_slug": "cacho",
    "population": 18569,
    "households": 6878,
    "occupied_dwellings": 6892,
    "avg_occupants": 2.6,
    "pct_internet": 83.8,
    "pct_car": 73.8,
    "pct_social_security": 74.9,
    "economically_active": 11433,
    "median_age": 36.6,
    "ageb_count": 8
  },
  {
    "zone_slug": "agua-caliente",
    "population": 9078,
    "households": 3502,
    "occupied_dwellings": 3503,
    "avg_occupants": 2.6,
    "pct_internet": 88.5,
    "pct_car": 83.5,
    "pct_social_security": 73.4,
    "economically_active": 5444,
    "median_age": 38.3,
    "ageb_count": 3
  },
  {
    "zone_slug": "lomas-de-agua-caliente",
    "population": 126439,
    "households": 37606,
    "occupied_dwellings": 37620,
    "avg_occupants": 3.4,
    "pct_internet": 73,
    "pct_car": 65.1,
    "pct_social_security": 75.3,
    "economically_active": 69111,
    "median_age": 30.4,
    "ageb_count": 37
  },
  {
    "zone_slug": "libertad",
    "population": 25398,
    "households": 8785,
    "occupied_dwellings": 8798,
    "avg_occupants": 2.8,
    "pct_internet": 76.6,
    "pct_car": 62.7,
    "pct_social_security": 61.7,
    "economically_active": 14408,
    "median_age": 35.1,
    "ageb_count": 7
  },
  {
    "zone_slug": "soler",
    "population": 76044,
    "households": 24701,
    "occupied_dwellings": 24732,
    "avg_occupants": 3.1,
    "pct_internet": 73.9,
    "pct_car": 61.4,
    "pct_social_security": 68.6,
    "economically_active": 41917,
    "median_age": 34,
    "ageb_count": 23
  },
  {
    "zone_slug": "federal",
    "population": 0,
    "households": 0,
    "occupied_dwellings": 0,
    "avg_occupants": 0,
    "pct_internet": 0,
    "pct_car": 0,
    "pct_social_security": 0,
    "economically_active": 0,
    "median_age": 0,
    "ageb_count": 0
  },
  {
    "zone_slug": "baja-malibu",
    "population": 17645,
    "households": 4917,
    "occupied_dwellings": 4921,
    "avg_occupants": 3.5,
    "pct_internet": 68.6,
    "pct_car": 62.5,
    "pct_social_security": 73.4,
    "economically_active": 9725,
    "median_age": 28,
    "ageb_count": 12
  },
  {
    "zone_slug": "real-del-mar",
    "population": 1978,
    "households": 511,
    "occupied_dwellings": 511,
    "avg_occupants": 3.8,
    "pct_internet": 60.7,
    "pct_car": 63.6,
    "pct_social_security": 66.3,
    "economically_active": 1011,
    "median_age": 25,
    "ageb_count": 2
  },
  {
    "zone_slug": "san-antonio-del-mar",
    "population": 1515,
    "households": 441,
    "occupied_dwellings": 441,
    "avg_occupants": 3.4,
    "pct_internet": 92.5,
    "pct_car": 95.5,
    "pct_social_security": 73.4,
    "economically_active": 732,
    "median_age": 29,
    "ageb_count": 1
  },
  {
    "zone_slug": "punta-bandera",
    "population": 0,
    "households": 0,
    "occupied_dwellings": 0,
    "avg_occupants": 0,
    "pct_internet": 0,
    "pct_car": 0,
    "pct_social_security": 0,
    "economically_active": 0,
    "median_age": 0,
    "ageb_count": 0
  },
  {
    "zone_slug": "costa-coronado",
    "population": 0,
    "households": 0,
    "occupied_dwellings": 0,
    "avg_occupants": 0,
    "pct_internet": 0,
    "pct_car": 0,
    "pct_social_security": 0,
    "economically_active": 0,
    "median_age": 0,
    "ageb_count": 0
  },
  {
    "zone_slug": "las-americas",
    "population": 40305,
    "households": 12053,
    "occupied_dwellings": 12060,
    "avg_occupants": 3.3,
    "pct_internet": 67.9,
    "pct_car": 61.7,
    "pct_social_security": 70,
    "economically_active": 21453,
    "median_age": 30.5,
    "ageb_count": 10
  },
  {
    "zone_slug": "villa-fontana",
    "population": 190103,
    "households": 55430,
    "occupied_dwellings": 55464,
    "avg_occupants": 3.4,
    "pct_internet": 75.5,
    "pct_car": 66.3,
    "pct_social_security": 73.9,
    "economically_active": 104801,
    "median_age": 29,
    "ageb_count": 68
  },
  {
    "zone_slug": "montecarlo",
    "population": 186335,
    "households": 53819,
    "occupied_dwellings": 53844,
    "avg_occupants": 3.5,
    "pct_internet": 78.8,
    "pct_car": 72.3,
    "pct_social_security": 72.5,
    "economically_active": 101938,
    "median_age": 29.1,
    "ageb_count": 62
  },
  {
    "zone_slug": "otay-universidad",
    "population": 8938,
    "households": 1521,
    "occupied_dwellings": 1524,
    "avg_occupants": 3.2,
    "pct_internet": 76.4,
    "pct_car": 68.6,
    "pct_social_security": 40.3,
    "economically_active": 2988,
    "median_age": 34,
    "ageb_count": 1
  },
  {
    "zone_slug": "santa-fe",
    "population": 46650,
    "households": 14545,
    "occupied_dwellings": 14546,
    "avg_occupants": 3.2,
    "pct_internet": 86.4,
    "pct_car": 79.6,
    "pct_social_security": 77.4,
    "economically_active": 25635,
    "median_age": 29.3,
    "ageb_count": 22
  },
  {
    "zone_slug": "natura",
    "population": 52018,
    "households": 15968,
    "occupied_dwellings": 15975,
    "avg_occupants": 3.3,
    "pct_internet": 75.3,
    "pct_car": 74.5,
    "pct_social_security": 75.1,
    "economically_active": 27920,
    "median_age": 29.1,
    "ageb_count": 33
  },
  {
    "zone_slug": "colinas-de-california",
    "population": 62948,
    "households": 19314,
    "occupied_dwellings": 19323,
    "avg_occupants": 3.3,
    "pct_internet": 76.6,
    "pct_car": 68.8,
    "pct_social_security": 73.3,
    "economically_active": 35280,
    "median_age": 31.7,
    "ageb_count": 16
  },
  {
    "zone_slug": "lomas-virreyes",
    "population": 38658,
    "households": 11864,
    "occupied_dwellings": 11872,
    "avg_occupants": 3.2,
    "pct_internet": 81.6,
    "pct_car": 73.8,
    "pct_social_security": 75.4,
    "economically_active": 21314,
    "median_age": 31.2,
    "ageb_count": 11
  },
  {
    "zone_slug": "insurgentes",
    "population": 25961,
    "households": 7653,
    "occupied_dwellings": 7658,
    "avg_occupants": 3.4,
    "pct_internet": 74,
    "pct_car": 72.2,
    "pct_social_security": 73.1,
    "economically_active": 14339,
    "median_age": 28.8,
    "ageb_count": 15
  },
  {
    "zone_slug": "el-florido",
    "population": 138914,
    "households": 40701,
    "occupied_dwellings": 40718,
    "avg_occupants": 3.4,
    "pct_internet": 64.2,
    "pct_car": 51.8,
    "pct_social_security": 77.7,
    "economically_active": 75760,
    "median_age": 26.8,
    "ageb_count": 66
  },
  {
    "zone_slug": "terrazas-de-la-presa",
    "population": 399917,
    "households": 115555,
    "occupied_dwellings": 115569,
    "avg_occupants": 3.5,
    "pct_internet": 66,
    "pct_car": 54.4,
    "pct_social_security": 79.1,
    "economically_active": 215435,
    "median_age": 26.1,
    "ageb_count": 147
  }
]

export function getZoneDemographics(slug: string): ZoneDemographics | null {
  return ZONE_DEMOGRAPHICS.find((d) => d.zone_slug === slug) ?? null
}

export function getAllDemographics(): ZoneDemographics[] {
  return ZONE_DEMOGRAPHICS
}
