/**
 * Demographic data per zone from INEGI Censo 2020 (SCINCE).
 * Generated by scripts/import-inegi.ts
 *
 * Source: INEGI SCINCE 2020 via SEDATU GeoServer
 * Note: Encuesta Intercensal 2025 estará disponible en septiembre 2026.
 */

export interface ZoneDemographics {
  zone_slug: string
  population: number
  households: number
  occupied_dwellings: number
  avg_occupants: number
  pct_internet: number
  pct_car: number
  pct_social_security: number
  economically_active: number
  median_age: number
  ageb_count: number
  // Extended variables (populated when shapefile has SCINCE fields)
  avg_education_years: number
  pop_no_schooling: number
  unemployed: number
  pct_computer: number
  pct_phone: number
  pct_washer: number
  pct_refrigerator: number
  pct_female: number
  pop_0_14: number
  pop_15_64: number
  pop_65_plus: number
  // Derived indicators
  nse_score: number
  nse_label: string
  dependency_ratio: number
  unemployment_rate: number
  economic_participation: number
  pop_density: number
}

const ZONE_DEMOGRAPHICS: ZoneDemographics[] = [
  {
    "zone_slug": "zona-rio",
    "population": 14136,
    "households": 5266,
    "occupied_dwellings": 5272,
    "avg_occupants": 2.6,
    "pct_internet": 75.2,
    "pct_car": 61.6,
    "pct_social_security": 61.8,
    "economically_active": 8328,
    "median_age": 35.3,
    "ageb_count": 7,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 65,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 58.9,
    "pop_density": 0
  },
  {
    "zone_slug": "playas-de-tijuana",
    "population": 78289,
    "households": 26302,
    "occupied_dwellings": 26326,
    "avg_occupants": 3,
    "pct_internet": 73.1,
    "pct_car": 59,
    "pct_social_security": 66.2,
    "economically_active": 45283,
    "median_age": 34.1,
    "ageb_count": 27,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 65,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 57.8,
    "pop_density": 0
  },
  {
    "zone_slug": "otay",
    "population": 130728,
    "households": 41557,
    "occupied_dwellings": 41606,
    "avg_occupants": 3.1,
    "pct_internet": 73.6,
    "pct_car": 64.1,
    "pct_social_security": 70.2,
    "economically_active": 72339,
    "median_age": 33,
    "ageb_count": 39,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 67,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 55.3,
    "pop_density": 0
  },
  {
    "zone_slug": "hipodromo-chapultepec",
    "population": 21850,
    "households": 7384,
    "occupied_dwellings": 7388,
    "avg_occupants": 3,
    "pct_internet": 93,
    "pct_car": 90.2,
    "pct_social_security": 78,
    "economically_active": 12474,
    "median_age": 39.7,
    "ageb_count": 7,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 81,
    "nse_label": "A/B",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 57.1,
    "pop_density": 0
  },
  {
    "zone_slug": "centro",
    "population": 24135,
    "households": 6874,
    "occupied_dwellings": 6887,
    "avg_occupants": 2.9,
    "pct_internet": 75.4,
    "pct_car": 63.1,
    "pct_social_security": 55.1,
    "economically_active": 11786,
    "median_age": 34.5,
    "ageb_count": 6,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 62,
    "nse_label": "C",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 48.8,
    "pop_density": 0
  },
  {
    "zone_slug": "residencial-del-bosque",
    "population": 210601,
    "households": 61268,
    "occupied_dwellings": 61291,
    "avg_occupants": 3.4,
    "pct_internet": 76.9,
    "pct_car": 65.8,
    "pct_social_security": 75.9,
    "economically_active": 115684,
    "median_age": 28.9,
    "ageb_count": 65,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 69,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 54.9,
    "pop_density": 0
  },
  {
    "zone_slug": "la-mesa",
    "population": 11987,
    "households": 3878,
    "occupied_dwellings": 3883,
    "avg_occupants": 3.1,
    "pct_internet": 77.9,
    "pct_car": 62.4,
    "pct_social_security": 68.6,
    "economically_active": 6839,
    "median_age": 33.1,
    "ageb_count": 4,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 68,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 57.1,
    "pop_density": 0
  },
  {
    "zone_slug": "cacho",
    "population": 0,
    "households": 0,
    "occupied_dwellings": 0,
    "avg_occupants": 0,
    "pct_internet": 0,
    "pct_car": 0,
    "pct_social_security": 0,
    "economically_active": 0,
    "median_age": 0,
    "ageb_count": 0,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 0,
    "nse_label": "D/E",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 0,
    "pop_density": 0
  },
  {
    "zone_slug": "agua-caliente",
    "population": 10949,
    "households": 3964,
    "occupied_dwellings": 3965,
    "avg_occupants": 2.7,
    "pct_internet": 88.5,
    "pct_car": 83.7,
    "pct_social_security": 75.4,
    "economically_active": 6387,
    "median_age": 36.1,
    "ageb_count": 4,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 78,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 58.3,
    "pop_density": 0
  },
  {
    "zone_slug": "lomas-de-agua-caliente",
    "population": 121277,
    "households": 35924,
    "occupied_dwellings": 35938,
    "avg_occupants": 3.4,
    "pct_internet": 72.5,
    "pct_car": 64.4,
    "pct_social_security": 75.1,
    "economically_active": 66157,
    "median_age": 30.3,
    "ageb_count": 35,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 68,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 54.6,
    "pop_density": 0
  },
  {
    "zone_slug": "libertad",
    "population": 13999,
    "households": 4822,
    "occupied_dwellings": 4827,
    "avg_occupants": 2.9,
    "pct_internet": 85.3,
    "pct_car": 76.6,
    "pct_social_security": 71,
    "economically_active": 7836,
    "median_age": 35.5,
    "ageb_count": 6,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 74,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 56,
    "pop_density": 0
  },
  {
    "zone_slug": "soler",
    "population": 57797,
    "households": 18552,
    "occupied_dwellings": 18561,
    "avg_occupants": 3.1,
    "pct_internet": 79.9,
    "pct_car": 74.1,
    "pct_social_security": 63.1,
    "economically_active": 29448,
    "median_age": 35,
    "ageb_count": 19,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 68,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 51,
    "pop_density": 0
  },
  {
    "zone_slug": "baja-malibu",
    "population": 0,
    "households": 0,
    "occupied_dwellings": 0,
    "avg_occupants": 0,
    "pct_internet": 0,
    "pct_car": 0,
    "pct_social_security": 0,
    "economically_active": 0,
    "median_age": 0,
    "ageb_count": 0,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 0,
    "nse_label": "D/E",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 0,
    "pop_density": 0
  },
  {
    "zone_slug": "real-del-mar",
    "population": 28240,
    "households": 7974,
    "occupied_dwellings": 7980,
    "avg_occupants": 3.5,
    "pct_internet": 68.1,
    "pct_car": 62.5,
    "pct_social_security": 71.5,
    "economically_active": 15275,
    "median_age": 27.9,
    "ageb_count": 23,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 65,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 54.1,
    "pop_density": 0
  },
  {
    "zone_slug": "san-antonio-del-mar",
    "population": 28549,
    "households": 8497,
    "occupied_dwellings": 8508,
    "avg_occupants": 3.3,
    "pct_internet": 75.9,
    "pct_car": 77,
    "pct_social_security": 72.2,
    "economically_active": 15637,
    "median_age": 30.8,
    "ageb_count": 26,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 71,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 54.8,
    "pop_density": 0
  },
  {
    "zone_slug": "punta-bandera",
    "population": 0,
    "households": 0,
    "occupied_dwellings": 0,
    "avg_occupants": 0,
    "pct_internet": 0,
    "pct_car": 0,
    "pct_social_security": 0,
    "economically_active": 0,
    "median_age": 0,
    "ageb_count": 0,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 0,
    "nse_label": "D/E",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 0,
    "pop_density": 0
  },
  {
    "zone_slug": "costa-coronado",
    "population": 41846,
    "households": 13185,
    "occupied_dwellings": 13191,
    "avg_occupants": 3.2,
    "pct_internet": 75.7,
    "pct_car": 72.3,
    "pct_social_security": 68,
    "economically_active": 21836,
    "median_age": 32.5,
    "ageb_count": 36,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 68,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 52.2,
    "pop_density": 0
  },
  {
    "zone_slug": "las-americas",
    "population": 49642,
    "households": 15299,
    "occupied_dwellings": 15308,
    "avg_occupants": 3.2,
    "pct_internet": 78.5,
    "pct_car": 69.7,
    "pct_social_security": 73.6,
    "economically_active": 28057,
    "median_age": 32.3,
    "ageb_count": 14,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 71,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 56.5,
    "pop_density": 0
  },
  {
    "zone_slug": "villa-fontana",
    "population": 186676,
    "households": 54472,
    "occupied_dwellings": 54504,
    "avg_occupants": 3.4,
    "pct_internet": 76,
    "pct_car": 67.1,
    "pct_social_security": 73.8,
    "economically_active": 102803,
    "median_age": 29.2,
    "ageb_count": 67,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 69,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 55.1,
    "pop_density": 0
  },
  {
    "zone_slug": "montecarlo",
    "population": 184073,
    "households": 52971,
    "occupied_dwellings": 52997,
    "avg_occupants": 3.5,
    "pct_internet": 78.6,
    "pct_car": 72,
    "pct_social_security": 72.5,
    "economically_active": 100548,
    "median_age": 29,
    "ageb_count": 61,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 71,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 54.6,
    "pop_density": 0
  },
  {
    "zone_slug": "otay-universidad",
    "population": 28371,
    "households": 8953,
    "occupied_dwellings": 8959,
    "avg_occupants": 3.1,
    "pct_internet": 80.6,
    "pct_car": 72.9,
    "pct_social_security": 71.4,
    "economically_active": 15937,
    "median_age": 34.6,
    "ageb_count": 11,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 71,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 56.2,
    "pop_density": 0
  },
  {
    "zone_slug": "santa-fe",
    "population": 52922,
    "households": 16648,
    "occupied_dwellings": 16651,
    "avg_occupants": 3.2,
    "pct_internet": 86.3,
    "pct_car": 81,
    "pct_social_security": 77.8,
    "economically_active": 29207,
    "median_age": 29.6,
    "ageb_count": 27,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 77,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 55.2,
    "pop_density": 0
  },
  {
    "zone_slug": "natura",
    "population": 136411,
    "households": 40073,
    "occupied_dwellings": 40083,
    "avg_occupants": 3.4,
    "pct_internet": 69.8,
    "pct_car": 63.6,
    "pct_social_security": 77,
    "economically_active": 73394,
    "median_age": 27.4,
    "ageb_count": 83,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 67,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 53.8,
    "pop_density": 0
  },
  {
    "zone_slug": "colinas-de-california",
    "population": 27572,
    "households": 7991,
    "occupied_dwellings": 7996,
    "avg_occupants": 3.4,
    "pct_internet": 71.5,
    "pct_car": 63.9,
    "pct_social_security": 73.3,
    "economically_active": 15132,
    "median_age": 28.8,
    "ageb_count": 6,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 67,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 54.9,
    "pop_density": 0
  },
  {
    "zone_slug": "lomas-virreyes",
    "population": 26072,
    "households": 8090,
    "occupied_dwellings": 8094,
    "avg_occupants": 3.2,
    "pct_internet": 81,
    "pct_car": 75.3,
    "pct_social_security": 78.3,
    "economically_active": 14681,
    "median_age": 30.5,
    "ageb_count": 12,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 74,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 56.3,
    "pop_density": 0
  },
  {
    "zone_slug": "insurgentes",
    "population": 77154,
    "households": 23017,
    "occupied_dwellings": 23036,
    "avg_occupants": 3.3,
    "pct_internet": 67.6,
    "pct_car": 58.8,
    "pct_social_security": 74.6,
    "economically_active": 42466,
    "median_age": 29.4,
    "ageb_count": 27,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 65,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 55,
    "pop_density": 0
  },
  {
    "zone_slug": "el-florido",
    "population": 106838,
    "households": 30724,
    "occupied_dwellings": 30734,
    "avg_occupants": 3.5,
    "pct_internet": 70.3,
    "pct_car": 63.7,
    "pct_social_security": 75.4,
    "economically_active": 57956,
    "median_age": 28,
    "ageb_count": 41,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 67,
    "nse_label": "C+",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 54.2,
    "pop_density": 0
  },
  {
    "zone_slug": "terrazas-de-la-presa",
    "population": 330145,
    "households": 96074,
    "occupied_dwellings": 96085,
    "avg_occupants": 3.4,
    "pct_internet": 65.4,
    "pct_car": 52.1,
    "pct_social_security": 80.1,
    "economically_active": 177835,
    "median_age": 25.7,
    "ageb_count": 124,
    "avg_education_years": 0,
    "pop_no_schooling": 0,
    "unemployed": 0,
    "pct_computer": 0,
    "pct_phone": 0,
    "pct_washer": 0,
    "pct_refrigerator": 0,
    "pct_female": 0,
    "pop_0_14": 0,
    "pop_15_64": 0,
    "pop_65_plus": 0,
    "nse_score": 63,
    "nse_label": "C",
    "dependency_ratio": 0,
    "unemployment_rate": 0,
    "economic_participation": 53.9,
    "pop_density": 0
  }
]

export function getZoneDemographics(slug: string): ZoneDemographics | null {
  return ZONE_DEMOGRAPHICS.find((d) => d.zone_slug === slug) ?? null
}

export function getAllDemographics(): ZoneDemographics[] {
  return ZONE_DEMOGRAPHICS
}

/** Compute NSE label from score */
export function getNseLabel(score: number): string {
  if (score >= 80) return "A/B"
  if (score >= 65) return "C+"
  if (score >= 50) return "C"
  if (score >= 35) return "C-"
  if (score >= 20) return "D+"
  return "D/E"
}

/** NSE color for badges/UI */
export function getNseColor(label: string): { bg: string; text: string } {
  switch (label) {
    case "A/B": return { bg: "bg-emerald-100 dark:bg-emerald-950", text: "text-emerald-700 dark:text-emerald-400" }
    case "C+": return { bg: "bg-blue-100 dark:bg-blue-950", text: "text-blue-700 dark:text-blue-400" }
    case "C": return { bg: "bg-sky-100 dark:bg-sky-950", text: "text-sky-700 dark:text-sky-400" }
    case "C-": return { bg: "bg-amber-100 dark:bg-amber-950", text: "text-amber-700 dark:text-amber-400" }
    case "D+": return { bg: "bg-orange-100 dark:bg-orange-950", text: "text-orange-700 dark:text-orange-400" }
    default: return { bg: "bg-red-100 dark:bg-red-950", text: "text-red-700 dark:text-red-400" }
  }
}

// ─── City-level averages for comparison bars ───

export function getCityDemographicAverages() {
  const all = ZONE_DEMOGRAPHICS.filter((d) => d.ageb_count > 0)
  const n = all.length || 1
  const totalPop = all.reduce((s, d) => s + d.population, 0)
  const totalDwellings = all.reduce((s, d) => s + d.occupied_dwellings, 0) || 1
  return {
    avg_pct_internet: Math.round(all.reduce((s, d) => s + d.pct_internet * d.occupied_dwellings, 0) / totalDwellings * 10) / 10,
    avg_pct_car: Math.round(all.reduce((s, d) => s + d.pct_car * d.occupied_dwellings, 0) / totalDwellings * 10) / 10,
    avg_pct_social_security: Math.round(all.reduce((s, d) => s + d.pct_social_security * d.occupied_dwellings, 0) / totalDwellings * 10) / 10,
    avg_median_age: Math.round(all.reduce((s, d) => s + d.median_age * d.population, 0) / (totalPop || 1) * 10) / 10,
    avg_occupants: Math.round(all.reduce((s, d) => s + d.avg_occupants, 0) / n * 10) / 10,
  }
}

// ─── Socioeconomic profile classification ───

export function classifySocioeconomicProfile(d: ZoneDemographics): string {
  if (d.nse_score >= 80) return "Premium"
  if (d.nse_score >= 65) return "Medio-Alto"
  if (d.nse_score >= 50) return "Medio"
  if (d.nse_score >= 35) return "Medio-Bajo"
  return "Popular"
}

export function getProfileColor(profile: string): string {
  switch (profile) {
    case "Premium": return "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-400"
    case "Medio-Alto": return "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-400"
    case "Medio": return "bg-sky-100 text-sky-700 dark:bg-sky-950 dark:text-sky-400"
    case "Medio-Bajo": return "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-400"
    default: return "bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-400"
  }
}

// ─── Buyer persona generator ───

import type { ZoneMetrics } from "@/types/database"

export function generateBuyerPersona(d: ZoneDemographics, zone: ZoneMetrics): { text: string; tags: string[] } {
  const tags: string[] = []
  let text = ""

  const profile = classifySocioeconomicProfile(d)
  const youngZone = d.median_age < 30
  const highInternet = d.pct_internet > 75
  const highCar = d.pct_car > 70
  const bigHousehold = d.avg_occupants > 3.5

  if (profile === "Premium" || profile === "Medio-Alto") {
    tags.push("Profesionistas", "Doble ingreso")
    if (highInternet) tags.push("Digitales")
    if (highCar) tags.push("Movilidad propia")
    text = youngZone
      ? "Parejas jóvenes profesionistas con alto poder adquisitivo, orientados a tecnología y servicios digitales."
      : "Familias establecidas con ingresos altos, buscan seguridad, espacio y plusvalía a largo plazo."
  } else if (profile === "Medio") {
    tags.push("Familias")
    if (bigHousehold) tags.push("Hogares grandes")
    if (youngZone) tags.push("Jóvenes")
    text = bigHousehold
      ? "Familias de clase media con hogares multigeneracionales, priorizan ubicación y acceso a servicios."
      : "Clase media trabajadora que busca estabilidad, buena conectividad y cercanía a empleo."
  } else {
    tags.push("Primera vivienda")
    if (youngZone) tags.push("Jóvenes")
    if (bigHousehold) tags.push("Familias extensas")
    text = "Familias en crecimiento buscando opciones accesibles. Alta sensibilidad al precio, priorizan espacio sobre ubicación."
  }

  if (d.pct_social_security > 75) tags.push("Empleo formal")
  if (d.economic_participation > 55) tags.push("Alta PEA")

  return { text, tags: tags.slice(0, 5) }
}

// ─── Opportunity score (0-100, 4 sub-scores of 25 each) ───

export function computeOpportunityScore(
  d: ZoneDemographics,
  zone: ZoneMetrics,
  allZones: ZoneMetrics[]
): { total: number; price_score: number; density_score: number; digital_score: number; economic_score: number } {
  const prices = allZones.filter((z) => z.avg_price_per_m2 > 0).map((z) => z.avg_price_per_m2)
  const maxPrice = Math.max(...prices, 1)
  const minPrice = Math.min(...prices, 0)
  const priceRange = maxPrice - minPrice || 1

  // Lower price = higher score (affordability)
  const priceNorm = 1 - (zone.avg_price_per_m2 - minPrice) / priceRange
  const price_score = Math.round(priceNorm * 25 * 10) / 10

  // Higher density = more demand potential
  const allDemo = ZONE_DEMOGRAPHICS.filter((dd) => dd.ageb_count > 0)
  const densities = allDemo.map((dd) => dd.population / (dd.ageb_count || 1))
  const maxDensity = Math.max(...densities, 1)
  const density_score = Math.round((d.population / (d.ageb_count || 1)) / maxDensity * 25 * 10) / 10

  // Digital connectivity
  const digital_score = Math.round(d.pct_internet / 100 * 25 * 10) / 10

  // Economic strength (PEA ratio + social security)
  const peaRatio = d.population > 0 ? d.economically_active / d.population : 0
  const ecoRaw = (peaRatio * 0.5 + d.pct_social_security / 100 * 0.5)
  const economic_score = Math.round(ecoRaw * 25 * 10) / 10

  const total = Math.round(price_score + density_score + digital_score + economic_score)

  return { total, price_score, density_score, digital_score, economic_score }
}

// ─── Market Intelligence insights (census × real estate) ───

export interface MarketInsight {
  id: string
  title: string
  zone_name: string
  zone_slug: string
  metric_value: string
  explanation: string
  icon: string
  accent: string
}

export function getMarketIntelligenceInsights(
  allDemo: ZoneDemographics[],
  zones: ZoneMetrics[],
  riskData: { zone_slug: string; risk_label: string; risk_score: number }[]
): MarketInsight[] {
  const insights: MarketInsight[] = []

  // 1. Highest opportunity zone (best combined score)
  let bestOpp = { slug: "", name: "", score: 0 }
  for (const demo of allDemo) {
    const zone = zones.find((z) => z.zone_slug === demo.zone_slug)
    if (!zone || zone.total_listings < 1) continue
    const opp = computeOpportunityScore(demo, zone, zones)
    if (opp.total > bestOpp.score) {
      bestOpp = { slug: zone.zone_slug, name: zone.zone_name, score: opp.total }
    }
  }
  if (bestOpp.slug) {
    insights.push({
      id: "best-opportunity",
      title: "Mayor Oportunidad",
      zone_name: bestOpp.name,
      zone_slug: bestOpp.slug,
      metric_value: `Score ${bestOpp.score}/100`,
      explanation: "Mejor combinación de precio accesible, densidad poblacional, conectividad digital y fuerza económica.",
      icon: "trending_up",
      accent: "border-l-emerald-500",
    })
  }

  // 2. Most underserved market (high population, low inventory)
  let bestUnderserved = { slug: "", name: "", ratio: 0, pop: 0 }
  for (const demo of allDemo) {
    const zone = zones.find((z) => z.zone_slug === demo.zone_slug)
    if (!zone || demo.population < 5000) continue
    const ratio = demo.population / (zone.total_listings || 1)
    if (ratio > bestUnderserved.ratio) {
      bestUnderserved = { slug: zone.zone_slug, name: zone.zone_name, ratio, pop: demo.population }
    }
  }
  if (bestUnderserved.slug) {
    insights.push({
      id: "underserved",
      title: "Mercado Desatendido",
      zone_name: bestUnderserved.name,
      zone_slug: bestUnderserved.slug,
      metric_value: `${Math.round(bestUnderserved.ratio).toLocaleString("es-MX")} hab/listing`,
      explanation: `${bestUnderserved.pop.toLocaleString("es-MX")} habitantes con poca oferta inmobiliaria activa. Potencial de demanda insatisfecha.`,
      icon: "group",
      accent: "border-l-blue-500",
    })
  }

  // 3. Most digital zone (highest internet penetration + highest NSE)
  const digitalSorted = [...allDemo].sort((a, b) => b.pct_internet - a.pct_internet)
  const topDigital = digitalSorted[0]
  if (topDigital) {
    const zone = zones.find((z) => z.zone_slug === topDigital.zone_slug)
    if (zone) {
      insights.push({
        id: "most-digital",
        title: "Más Conectada",
        zone_name: zone.zone_name,
        zone_slug: zone.zone_slug,
        metric_value: `${topDigital.pct_internet}% internet`,
        explanation: "Zona con mayor penetración digital. Ideal para estrategias de marketing online y proptech.",
        icon: "wifi",
        accent: "border-l-violet-500",
      })
    }
  }

  // 4. Lowest risk + high economy
  const stableZones = riskData.filter((r) => r.risk_label === "Bajo")
  let bestStable = { slug: "", name: "", pea: 0 }
  for (const r of stableZones) {
    const demo = allDemo.find((d) => d.zone_slug === r.zone_slug)
    if (!demo) continue
    const zone = zones.find((z) => z.zone_slug === r.zone_slug)
    if (!zone) continue
    const peaRatio = demo.population > 0 ? demo.economically_active / demo.population * 100 : 0
    if (peaRatio > bestStable.pea) {
      bestStable = { slug: zone.zone_slug, name: zone.zone_name, pea: peaRatio }
    }
  }
  if (bestStable.slug) {
    insights.push({
      id: "stable-economy",
      title: "Estable y Productiva",
      zone_name: bestStable.name,
      zone_slug: bestStable.slug,
      metric_value: `${Math.round(bestStable.pea)}% PEA`,
      explanation: "Riesgo bajo y alta participación económica. Perfil ideal para inversión conservadora a largo plazo.",
      icon: "shield",
      accent: "border-l-amber-500",
    })
  }

  return insights
}
